# Generated by Django 5.2.3 on 2025-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='produto',
            name='link_mercado_livre',
            field=models.URLField(blank=True, null=True),
        ),
    ]
